version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm run start-watch
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV}
      WEBTRENDS_ANALYTICS_TRACKING_ID: ${WEBTRENDS_ANALYTICS_TRACKING_ID-WT1}
      GOOGLE_ANALYTICS_TRACKING_ID: ${GOOGLE_ANALYTICS_TRACKING_ID}
      HOTJAR_ANALYTICS_TRACKING_ID: ${HOTJAR_ANALYTICS_TRACKING_ID-0}

  profiles-frontend:
    extends:
      service: base-app
    links:
    - profiles-db:mongo
    ports:
      - 3000:3000
    volumes:
      - profiles-node_modules:/code/node_modules

  profiles-db:
    image: "nhsuk/profiles-db:${profiles_db_docker_image_tag-0.7.5}"

volumes:
  profiles-node_modules:
